name: Build & deploy
on:
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./gradlew clean build -PbotToken=${{ secrets.botToken }} -PdbUrl=${{ DB_URL }} -PdbUsername=${{ DB_USERNAME }} -PdbPassword=${{ DB_PASSWORD }}
      - run: echo "Build Complete"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build/libs