name: Build & deploy
on:
  push:
    branches:
      - master
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./gradlew clean build -PbotToken=${{ secrets.botToken }} -PdbUrl=${{ secrets.DB_URL }} -PdbUsername=${{ secrets.DB_USERNAME }} -PdbPassword=${{ secrets.DB_PASSWORD }}
      - run: echo "Build Complete"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build/libs
      - name: Stop bot with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo systemctl stop okbot
      - name: copy jar via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          source: "${{ github.workspace }}/build/libs/okbot-0.0.1-SNAPSHOT.jar"
          target: "bot"
          rm: true
      - name: Run bot with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo systemctl start okbot